name: recipe_daily
description: "An app that suggests recipes and calculates calories automatically."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8

  # Flutter Icon and Splash Screen
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  # Firebase Packages
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  
  # Email Sending
  mailer: ^6.5.0

  # Google Sign In
  google_sign_in: ^6.2.0

  # State Management
  provider: ^6.1.1

  # HTTP and Local Storage
  http: ^1.5.0
  shared_preferences: ^2.1.1

  # SQLite for Local Database
  sqflite: ^2.4.1
  path: ^1.9.1 # Path utilities for SQLite
  path_provider: ^2.1.5 # Get application documents directory

  # Image and Video Handling
  image_picker: ^1.0.7 
  video_player: ^2.8.2     
  cached_network_image: ^3.3.1  
  flutter_cache_manager: ^3.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/data/calories.json

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter_native_splash:
  background_image: assets/images/splash_background.png
  image: assets/icons/splash_icon.png

  android_12:
    color: "#0F2484"
    image: assets/icons/splash_icon.png
